### PR TITLE
Revert "Guard linux-specific code"

### PR DESCRIPTION
**Pull request by dham**
Reverts firedrakeproject/VTKPythonPackage#1

### CODE REVIEW

**Comment by JDBetteridge** [comment]
Did this break the build process? We probably need an else on your reverted change that applies [delocate](https://github.com/matthew-brett/delocate) which is the MacOS equivalent of auditwheel.

**Comment by dham** [comment]
> Did this break the build process? We probably need an else on your reverted change that applies [delocate](https://github.com/matthew-brett/delocate) which is the MacOS equivalent of auditwheel.

It didn't break it, I just accidentally merged because there are no protections on this repo.

**Comment by JDBetteridge** [comment]
Fixed!

**Comment by JDBetteridge** [comment]
Superseded

**Pull request closed without merging**
